import type { NextPage } from 'next';
import Head from 'next/head';
import CoffeeBtn from '../components/coffeeBtn';
import Form from '../components/form';
import Toggle from '../components/toggle';
import { FaTwitterSquare, FaGlobe, FaGithub } from 'react-icons/fa';

const Home: NextPage = () => {
  return (
    <div className='sm:py-0 pt-8 px-8'>
      <Head>
        <title>Twitter Analyzer 🥸</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='absolute right-0 sm:px-11 px-5 py-14'>
        <Toggle />
      </div>

      <main className='min-h-[90vh] flex flex-col justify-center items-center flex-[1]'>
        <h1 className='m-0 sm:text-6xl text-3xl'>Twitter Declutter 🐦</h1>

        <h2 className='text-center sm:my-16 my-4 mx-0 sm:text-xl text-lg'>
          See which users you&apos;ve been liking recently
        </h2>
        <Form />
      </main>

      <footer className='lg:inline-grid lg:grid-cols-3 flex flex-col w-full py-8 mx-auto border-t border-[#eaeaea] items-center'>
        <div></div>
        <a
          href='aroze.xyz'
          target='_blank'
          rel='noopener noreferrer'
          className='lg:justify-self-center lg:py-0 pb-3'
        >
          Created by roze 🌹
        </a>
        <div className='inline-flex items-center justify-center lg:py-0 pt-3'>
          <a
            href='https://aroze.xyz/'
            className='text-xl px-2 dark:hover:text-indigo-200 hover:text-indigo-300 transition duration-200'
            target='_blank'
            rel='noreferrer'
          >
            <FaGlobe />
          </a>
          <a
            href='https://twitter.com/emotionldaffodl'
            className='text-xl px-2 dark:hover:text-indigo-200 hover:text-indigo-300 transition duration-200'
            target='_blank'
            rel='noreferrer'
          >
            <FaTwitterSquare />
          </a>
          <a
            href='https://github.com/elewis9989'
            className='text-xl px-2 dark:hover:text-indigo-200 hover:text-indigo-300 transition duration-200'
            target='_blank'
            rel='noreferrer'
          >
            <FaGithub />
          </a>
          <div className='px-4'>
            <CoffeeBtn />
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;
