import type { NextPage } from 'next';
import Head from 'next/head';
import Form from '../components/form';
import Toggle from '../components/toggle';

const Home: NextPage = () => {
  return (
    <div className='py-0 px-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='absolute right-0 px-11 py-14'>
        <Toggle />
      </div>

      <main className='min-h-[90vh] flex flex-col justify-center items-center flex-[1]'>
        <h1 className='m-0 text-6xl dark:text-red-600'>Twitter Declutter 🐦</h1>

        <h2 className='text-center my-16 mx-0 text-xl'>
          See which users you&apos;ve been liking recently
        </h2>
        <Form />
      </main>

      <footer className='flex flex-[1] py-8 px-0 border-t border-[#eaeaea] justify-center items-center'>
        <a
          href='aroze.xyz'
          target='_blank'
          rel='noopener noreferrer'
          className='flex justify-center items-center flex-grow'
        >
          Created by roze 🌹
        </a>
      </footer>
    </div>
  );
};

export default Home;
